[project]
name = "airflow-dags"
version = "0.1.0"
description = "Airflow DAGs and dependencies"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.4",
    "boto3>=1.34.0",
    "botocore>=1.34.0",
]

[dependency-groups]
dev = [
    "apache-airflow-task-sdk>=1.0.3",
]
